config/routes.rb
Taskman::Application.routes.draw do

  resources :users#, :only => :new
  resources :sessions, :only => [:new, :create, :destroy]

  resources :lists do
    resources :tasks do
      resources :comments
      collection { post :sort }
      member do
        post 'toggle'
      end
    end
  end

  match '/register' => 'users#new'
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  
  root :to => 'lists#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :task_id, :user_id
  belongs_to :user
  belongs_to :task
  validates :body, :presence => true, :length => { :minimum => 2 }
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name
  has_many :tasks, :dependent => :destroy
  validates :name, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :title, :completed, :description, :due_date, :list_id, :user_id
  belongs_to :list
  belongs_to :user
  has_many :comments, :dependent => :destroy
  
  validates :title, :presence => true
  
  scope :completed, where(:completed => true)
  scope :incomplete, where(:completed => false)
  scope :due_today, where("due_date = ?", Time.now.to_date)
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :username, :password, :password_confirmation
  username_regex = /^[\w]+$/i
  
  validates :name, :presence => true, :length => { :within => 3..50 }
  validates :username,
    :presence   => true,
    :length     => { :within => 3..15 },
    :format     => { :with => username_regex },
    :uniqueness => { :case_sensitive => false }
    
  has_secure_password
  has_many :tasks
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
    
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
    
    def authorize
      redirect_to login_url, alert: "Please login or register an account." if current_user.nil?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :js
  def create
    @list = List.find(params[:list_id])
    @comment = Comment.new(params[:comment])
    @task = @comment.task_id
    @comment.save
    # redirect_to list_task_url(@list, @task)
    respond_with @comment, :location => list_task_url(@list, @task)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authorize

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks.order("position, created_at")
    @task = @list.tasks.new
    @title = @list.name
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(params[:list])

    if @list.save
      redirect_to @list
    else
      render action: "new"
    end
  end

  def update
    @list = List.find(params[:id])

    if @list.update_attributes(params[:list])
      redirect_to @list
    else
      render action: "edit"
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to root_url, notice: "You are already logged in."
    end
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid username or password! Try again."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authorize

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @list = @task.list
    @comments = @task.comments.all
    @comment = Comment.new
    @title = @list.name
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
    @list = @task.list
    @title = @list.name
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(params[:task])

    if @task.save
      redirect_to list_url(@list), notice: 'Task was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @task = Task.find(params[:id])
    @list = @task.list

    if @task.update_attributes(params[:task])
      redirect_to list_task_url, notice: 'Task was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @list = List.find(params[:list_id])
    @task.destroy
    redirect_to list_url(@list)
  end
  
  def toggle
    @task = Task.find(params[:id])
    @list = List.find(params[:list_id])
    @task.toggle!(:completed)
    redirect_to list_url(@list)
  end
  
  def sort
    params[:task].each_with_index do |id, index|
      Task.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, :except => [:new, :create]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    if current_user
      redirect_to root_url, notice: "You are already logged in."
    else
      @user = User.new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to login_url, notice: "Your account was created. Please login now."
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
  
  # Return a title on a per-page basis.
  def title
    base_title = "Taskman"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    image_tag('logo.png', :alt => "Taskman", :title => "Taskman")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def assigned_person
    if @task.user
    	"Assigned person: #{@task.user.name}"
    else
    	"No assigned person"
    end 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= content_tag_for :div, comment do %>
	<h5>
		<%= comment.user.name  %>
		<small>
			(<%= time_ago_in_words(comment.created_at) %> ago)
			<%= link_to("×", list_task_comment_url(@list, @task, comment), method: :delete, remote: true, format: :js) if comment.user == current_user %>
		</small>
	</h5>
	<%= markdown comment.body %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@list, @task, @comment], :html => { :id => "new-comment-form" }, :remote => true do |f| %>
	<fieldset>
		<div class="control-group">
			<div class="controls">
				<%= f.hidden_field :task_id, :value => @task.id %>
				<%= f.hidden_field :user_id, :value => current_user.id %>
				<%= f.text_area :body, :placeholder => "Enter your comment", :rows => 3, :class => "span6" %><br />
				<%= f.submit "Post comment", :class => "btn" %>
			</div>
		</div>
	</fieldset>
<% end %>

app/views/comments/create.js.erb
$('<%= escape_javascript(render :partial => @comment) %>')
  .appendTo('#comments')
	.hide()
  .fadeIn()
$('#new-comment-form')[0].reset()

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id%>')
	.fadeOut()
	

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= title %></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
		<meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple Taskmanager built with Rails">
    <meta name="author" content="Artem Pakk">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  <body>

    <div class="container">
			<div class="row" id="header">
				<div class="span5">
					<%= link_to logo, root_url %>
				</div>
				<div class="span5">
					<p class="pull-right">
					<% if current_user %>
						<%= current_user.name %> |
						<%= link_to "Log out", logout_url %>
					<% end %>
					</p>
				</div>
			</div>
      <div class="row">
      	<div class="span10">
      		<%= render 'layouts/messages' %>
					<%= yield %>
      	</div>
			</div>

      <hr>

      <footer>
        <p>
					<small>&copy; 2012 Artem Pakk</small>
				</p>
      </footer>

    </div>

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, :html => { :class => "form-inline" } do |f| %>
  <% if @list.errors.any? %>
    <div class="alert alert-error">
      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
	<% end %>
	
	<fieldset>
		<div class="control-group">
			<div class="controls">
				<%= f.text_field :name, :placeholder => "List name" %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<%= f.submit :class => "btn" %>
			</div>
		</div>
	</fieldset>

<% end %>

app/views/lists/_list.html.erb
<%= content_tag_for :div, list do %>
	<h3>
		<%= link_to list.name, list %>
		<small class="pull-right">
			<%= link_to 'edit', edit_list_path(list) %> | <%= link_to 'delete', list, method: :delete, data: { confirm: 'Are you sure to delete this list and all its tasks?' } %>
		</small>
	</h3>
	<p>
		<%= list.tasks.count %> total &bull;
		<%= list.tasks.incomplete.count %> incomplete &bull;
		<%= list.tasks.incomplete.due_today.count %> due today
	</p>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', root_url %>

app/views/lists/index.html.erb
<h2>Lists</h2>
<%= render @lists %>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h2>New list</h2>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/lists/show.html.erb
<ul class="breadcrumb">
	<li>
		<%= link_to "Lists", root_url %> <span class="divider">/</span>
	</li>
	<li>
		 <%= @list.name %>
	</li>
</ul>
<h2><%= best_in_place @list, :name %></h2>
<%= link_to "New Task", "#new-task", :id => "new-task", :class => "btn" %>

<%= form_for [@list, @task], :html => { :id => "new-task-form" } do |f| %>
	<fieldset>
		<div class="control-group">
			<div class="controls">
				<%= f.text_field :title, :placeholder => "Task", :class => "span6" %><br />
				<%= f.text_area :description, :placeholder => "Description", :rows => 3, :class => "span6" %><br />
				<%= f.text_field :due_date, :class => "datepicker", :placeholder => "Due date" %>
				<%= collection_select(:task, :user_id, User.all, :id, :name, :prompt => "Assigned person") %><br />
				<%= f.submit :class => "btn" %>
				<%= link_to "Cancel", "#", :id => "cancel", :class => "btn" if @task.new_record? %>
			</div>
		</div>
	</fieldset>
<% end %>

<div id="tasks" data-update-url="<%= sort_list_tasks_url(@list, @task) %>">
	<%= render @tasks %>
</div>

app/views/tasks/_form.html.erb
<%= form_for [@list, @task] do |f| %>
<% if @task.errors.any? %>
  <div class="alert alert-error">
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
	<fieldset>
		<div class="control-group">
			<div class="controls">
				<%= f.text_field :title, :placeholder => "Task", :class => "span6" %><br />
				<%= f.text_area :description, :placeholder => "Description", :rows => 6, :class => "span6" %><br />
				<%= f.text_field :due_date, :class => "datepicker", :placeholder => "Due date" %>
				<%= collection_select(:task, :user_id, User.all, :id, :name, :prompt => "Assigned person") %><br />
				<%= f.submit :class => "btn" %>
			</div>
		</div>
	</fieldset>
<% end %>

app/views/tasks/_status.html.erb
<% if @task.completed %>
	<%= link_to image_tag('checkbox-checked.png'), toggle_list_task_url(@list, @task), :method => :post, :remote => true %>
<% else %>
	<%= link_to image_tag('checkbox.png'), toggle_list_task_url(@list, @task), :method => :post, :remote => true %>
<% end %>

app/views/tasks/_task.html.erb
<%= content_tag_for :div, task do %>
	<h3>
		<% if task.completed %>
			<%= link_to image_tag('checkbox-checked.png'), toggle_list_task_url(@list, task), :method => :post %>
		<% else %>
			<%= link_to image_tag('checkbox.png'), toggle_list_task_url(@list, task), :method => :post %>
		<% end %>
		<%= link_to task.title, list_task_url(@list, task) %>		
		<small class="pull-right">
			<% if task.description? %>
				<i class="icon-asterisk" title="Task has description"></i>
			<% end %>
			<% if task.comments.count > 0 %>
				<i class="icon-comment" title="Task has comments"></i>
			<% end %>
			<% if task.user %>
				<span class="user"><%= task.user.name %></span>
			<% end %>
			<% if task.due_date && !task.completed? %>
				<% if task.due_date == Time.now.to_date %>
					<span class="due today">Today</span>
				<% elsif task.due_date == Time.now.to_date + 1.day %>
					<span class="due tomorrow">Tomorrow</span>
				<% elsif task.due_date.past? %>
					<span class="due overdue"><%= distance_of_time_in_words(task.due_date, Time.now.to_date) %> overdue</span>
				<% else %>
					<span class="due"><%= task.due_date %></span>
				<% end %>
			<% end %>
		</small>
	</h3>
<% end %>

app/views/tasks/edit.html.erb
<ul class="breadcrumb">
	<li>
		<%= link_to "Lists", root_url %> <span class="divider">/</span>
	</li>
	<li>
		<%= link_to @task.list.name, list_url(@task.list) %>
	</li>
</ul>
<hr />

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Due date</th>
    <th>Completed</th>
    <th>List</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= task.due_date %></td>
    <td><%= task.completed %></td>
    <td><%= task.list_id %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<ul class="breadcrumb">
	<li>
		<%= link_to "Lists", root_url %> <span class="divider">/</span>
	</li>
	<li>
		<%= link_to @task.list.name, list_url(@task.list) %>
	</li>
</ul>
<hr />
<h3>
	<% if @task.completed %>
		<%= link_to image_tag('checkbox-checked.png'), toggle_list_task_url(@list, @task), :method => :post %>
	<% else %>
		<%= link_to image_tag('checkbox.png'), toggle_list_task_url(@list, @task), :method => :post %>
	<% end %>
	<%= @task.title %>
	<small class="pull-right">
		<%= link_to "edit", edit_list_task_url(@list, @task) %> |
		<%= link_to "delete", list_task_url(@list, @task), method: :delete, data: { confirm: 'Are you sure?' }%>
	</small>
</h3>
<hr />
<% if @task.due_date %>
	<p>Due date:
	<% if @task.due_date == Time.now.to_date %>
		Today
	<% elsif @task.due_date == Time.now.to_date + 1.day %>
		Tomorrow
	<% elsif @task.due_date.past? %>
		<%= "#{@task.due_date.to_s(:full)} (#{distance_of_time_in_words(@task.due_date, Time.now.to_date)} ago)" %>
	<% else %>
		<%= "#{@task.due_date.to_s(:full)} (in #{distance_of_time_in_words(@task.due_date, Time.now.to_date)})" %>
	<% end %>
	</p>
<% end %>
<p><%= assigned_person %></p>
<%= markdown @task.description %>

<hr />
<div id="comments">
	<h4>Comments:</h4>
	<%= render @comments %>
</div>

<%= render 'comments/form' %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-vertical" } do |f| %>
<% if @user.errors.any? %>
  <div class="alert alert-error">
		<a class="close" data-dismiss="alert" href="#">×</a>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

	<fieldset>
		<div class="control-group">
			<%= f.label :name, "Full name", :class => "control-label" %>
			<div class="controls">
				<%= f.text_field :name %>
			</div>
		</div>
		
		<div class="control-group">
			<%= f.label :username, "Pick a username", :class => "control-label" %>
			<div class="controls">
				<%= f.text_field :username %>
			</div>
		</div>
		
		<div class="control-group">
	  	<%= f.label :password, :class => "control-label" %>
	  	<div class="controls">
	  		<%= f.password_field :password, :class => "input-large" %>
	  	</div>
		</div>
		
		<div class="control-group">
	  	<%= f.label :password_confirmation, :class => "control-label" %>
	  	<div class="controls">
	  		<%= f.password_field :password_confirmation, :class => "input-large" %>
	  	</div>
		</div>
		
		<div class="control-group">
	  	<div class="controls">
	  		<%= f.submit "Register", :class => "btn" %>
				<%= link_to "Already registered? Login here", login_url %>
	  	</div>
		</div>
	</fieldset>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create an account</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>